# Backend (API)
FROM node:22.16.0 AS api

RUN apt-get update && apt-get install -y \
  python3 \
  make \
  g++ \
  ffmpeg \
  libpangocairo-1.0-0 \
  libcairo2-dev \
  libjpeg-dev \
  libpango1.0-dev \
  libgif-dev \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the backend source code
COPY . .

# Expose the API port
EXPOSE 3000

# Start the backend server
CMD ["node", "index.js"]